var dataUrl = [

'https://pastelink.in/v/?id=RX7LN44',
'https://pastelink.in/v/?id=Q229XWC',
'https://pastelink.in/v/?id=3ETVQKW',
'https://pastelink.in/v/?id=U5XQXF2',
'https://pastelink.in/v/?id=QU6W4UW',
'https://pastelink.in/v/?id=YI9X6QD',
'https://pastelink.in/v/?id=EA6WSZM',
'https://pastelink.in/v/?id=H6Y39RF',
'https://pastelink.in/v/?id=92HIU8X',
'https://pastelink.in/v/?id=WE04VQW',
'https://pastelink.in/v/?id=1NUDYB4',
'https://pastelink.in/v/?id=72DQPOD',
'https://pastelink.in/v/?id=A4G1Q97',
'https://pastelink.in/v/?id=M9Y5K2D',
'https://pastelink.in/v/?id=P8LPW7V',
'https://billimiters.ayoah.com/videy',
'https://billimiters.ayoah.com/videy',
'https://billimiters.ayoah.com/videy',
'https://billimiters.ayoah.com/videy',
'https://billimiters.ayoah.com/videy',
'https://billimiters.ayoah.com/videy',
'https://billimiters.ayoah.com/videy',
'https://billimiters.ayoah.com/videy',
'https://billimiters.ayoah.com/videy',
'https://billimiters.ayoah.com/videy',
'https://billimiters.ayoah.com/videy',
'https://billimiters.ayoah.com/whatsapp',
'https://billimiters.ayoah.com/whatsapp',
'https://billimiters.ayoah.com/whatsapp',
'https://billimiters.ayoah.com/whatsapp',
'https://billimiters.ayoah.com/dating',
'https://billimiters.ayoah.com/dating',
'https://billimiters.ayoah.com/dating',
'https://billimiters.ayoah.com/dating',
'https://billimiters.ayoah.com/dating',
'https://billimiters.ayoah.com/dating',
'https://billimiters.ayoah.com/dating',
'https://billimiters.ayoah.com/dating',
'https://billimiters.ayoah.com/dating'

];
var randomItem = dataUrl[Math.floor(Math.random()*dataUrl.length)];
window.location = randomItem;
