var dataUrl = [

'https://chattwhatsapvideo.blogspot.com/2025/08/play-video-50.html',
'https://chattwhatsapvideo.blogspot.com/2025/08/play-video-49.html',
'https://chattwhatsapvideo.blogspot.com/2025/08/play-video-48.html',
'https://chattwhatsapvideo.blogspot.com/2025/08/play-video-47.html',
'https://chattwhatsapvideo.blogspot.com/2025/08/play-video-46.html',
'https://chattwhatsapvideo.blogspot.com/2025/08/play-video-45.html',
'https://chattwhatsapvideo.blogspot.com/2025/08/play-video-44.html',
'https://chattwhatsapvideo.blogspot.com/2025/08/play-video-43.html',
'https://chattwhatsapvideo.blogspot.com/2025/08/play-video-42.html',
'https://chattwhatsapvideo.blogspot.com/2025/08/play-video-41.html',
'https://chattwhatsapvideo.blogspot.com/2025/08/play-video-39.html',
'https://chattwhatsapvideo.blogspot.com/2025/08/play-video-38.html',
'https://chattwhatsapvideo.blogspot.com/2025/08/play-video-37.html',
'https://chattwhatsapvideo.blogspot.com/2025/08/play-video-36.html',
'https://chattwhatsapvideo.blogspot.com/2025/08/play-video-35.html',
'https://chattwhatsapvideo.blogspot.com/2025/08/play-video-34.html',
'https://chattwhatsapvideo.blogspot.com/2025/08/play-video-33.html',
'https://chattwhatsapvideo.blogspot.com/2025/08/play-video-32.html',
'https://chattwhatsapvideo.blogspot.com/2025/08/play-video-31.html',
'https://chattwhatsapvideo.blogspot.com/2025/08/play-video-30.html',
'https://chattwhatsapvideo.blogspot.com/2025/08/play-video-29.html',
'https://billimiters.ayoah.com/videy',
'https://billimiters.ayoah.com/videy',
'https://billimiters.ayoah.com/videy',
'https://billimiters.ayoah.com/videy',
'https://billimiters.ayoah.com/videy',
'https://billimiters.ayoah.com/whatsapp',
'https://billimiters.ayoah.com/whatsapp',
'https://billimiters.ayoah.com/whatsapp',
'https://billimiters.ayoah.com/whatsapp',
'https://billimiters.ayoah.com/whatsapp',
'https://billimiters.ayoah.com/whatsapp',
'https://billimiters.ayoah.com/whatsapp',
'https://billimiters.ayoah.com/dating',
'https://billimiters.ayoah.com/dating',
'https://billimiters.ayoah.com/dating',
'https://billimiters.ayoah.com/dating',
'https://billimiters.ayoah.com/dating',
'https://billimiters.ayoah.com/dating',
'https://billimiters.ayoah.com/dating',
'https://billimiters.ayoah.com/dating',
'https://billimiters.ayoah.com/dating'

];
var randomItem = dataUrl[Math.floor(Math.random()*dataUrl.length)];
window.location = randomItem;
