var dataUrl = [

'https://fullvideooplaynew1.blogspot.com/',
'https://fullvideooplaynew2.blogspot.com/',
'https://fullvideooplaynew3.blogspot.com/',
'https://fullvideooplaynew4.blogspot.com/',
'https://fullvideooplaynew5.blogspot.com/',
'https://fullvideooplaynew6.blogspot.com/',
'https://fullvideooplaynew7.blogspot.com/',
'https://fullvideooplaynew8.blogspot.com/',
'https://fullvideooplaynew9.blogspot.com/',
'https://fullvideooplaynew10.blogspot.com/',
'https://fullvideooplaynew11.blogspot.com/',
'https://fullvideooplaynew12.blogspot.com/',
'https://fullvideooplaynew13.blogspot.com/',
'https://fullvideooplaynew14.blogspot.com/',
'https://fullvideooplaynew15.blogspot.com/',
'https://fullvideooplaynew17.blogspot.com/',
'https://fullvideooplaynew18.blogspot.com/',
'https://fullvideooplaynew19.blogspot.com/',
'https://fullvideooplaynew20.blogspot.com/',
'https://videoplaywfullvirall1.blogspot.com/',
'https://videoplaywfullvirall2.blogspot.com/',
'https://videoplaywfullvirall3.blogspot.com/',
'https://videoplaywfullvirall4.blogspot.com/',
'https://videoplaywfullvirall5.blogspot.com/',
'https://videoplaywfullvirall6.blogspot.com/',
'https://videoplaywfullvirall7.blogspot.com/',
'https://videoplaywfullvirall8.blogspot.com/',
'https://videoplaywfullvirall9.blogspot.com/',
'https://videoplaywfullvirall10.blogspot.com/',
'https://videoplaywfullvirall11.blogspot.com/',
'https://videoplaywfullvirall12.blogspot.com/',
'https://videoplaywfullvirall13.blogspot.com/',
'https://videoplaywfullvirall14.blogspot.com/',
'https://videoplaywfullvirall15.blogspot.com/',
'https://videoplaywfullvirall16.blogspot.com/',
'https://videoplaywfullvirall17.blogspot.com/',
'https://videoplaywfullvirall18.blogspot.com/',
'https://videoplaywfullvirall19.blogspot.com/',
'https://videoplaywfullvirall20.blogspot.com/'

];
var randomItem = dataUrl[Math.floor(Math.random()*dataUrl.length)];
window.location = randomItem;
